title: "Web Development Workshop"
author: "Navie Vurdien"
description: "Here are some tutorials on Web Development!"
more: "read more »"
url: "https://nvurdien.github.io"
baseurl: "/webdev-workshop" # comment out if in root directory

style:
  body: 'white' # main background color
  padding: 3 # factor for the padding width
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  nav: "#222" # color of the header and footer
  uppercase: true # use uppercase text for headings
  margin: 0% # increase to add a margin to the left and right side
  margincolor: "#f0f0f0" # only relevant if margin is non-zero

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/nvurdien/", square: true}
  - linkedin: {url: "https://www.linkedin.com/in/nvurdien/", square: true}
  - globe: {url: "https://nvurdien.github.io/", square: false}
  - envelope: {url: "mailto:nvurdien@gmail.com", square: true}

collections:
  pages:
    output: true
    permalink: /:collection/:path/



paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
